import test from 'node:test';import assert from 'node:assert/strict';import * as B from '../dist/battle.js';import * as R from '../dist/run.js';import {derive} from '../dist/math.js';
const make=(allies=['amiya'])=>B.newBattle({art:'AK018',stats:derive(Array(5).fill(3))},{id:'test',title:'团队回归',allies,enemies:['heavy']},{config:{aiEvaluation:true}});
const fallen=b=>{const p=b.units[0],e=b.units.find(u=>u.side==='enemy');B.damage(b,e,p,1e8,'true',100,{indirect:true,ignoreShield:true});B.checkEnd(b);return p;};
test('player death does not end combat; allied AI can win without player input',()=>{const b=make(),p=fallen(b);b.config={skipIntents:true};assert.equal(p.hp,0);assert.equal(b.over,null);const e=b.units.find(u=>u.side==='enemy');e.hp=1;e.shields=[];for(let i=0;i<30&&!b.over;i++){B.advance(b);if(b.actor){const u=b.units.find(u=>u.id===b.actor);assert.notEqual(u.id,p.id);const a=B.chooseAI(b,u);B.act(b,a.button,a.target,a.choice||{});}}assert.equal(b.over?.won,true);});
test('live allied summon survives owner death and can finish the battle alone',()=>{const b=make([]),p=b.units[0],pet=B.spawn(b,p,{name:'训练狼',h:.4,a:4,basis:'P',v:100,duration:3,limit:1});fallen(b);assert.equal(pet.removed,false);assert.equal(b.over,null);const e=b.units.find(u=>u.side==='enemy');e.hp=1;e.shields=[];b.actor=pet.id;B.act(b,'martial',e.id);assert.equal(b.over.won,true);});
test('orphan summon duration is finite and expiry does not award a kill',()=>{const b=make([]),p=b.units[0],pet=B.spawn(b,p,{name:'临时狼',h:.4,a:.1,basis:'P',v:100,duration:1,limit:1});fallen(b);pet.turn=pet.orphanExpires;pet.gauge=100;b.actor=null;B.advance(b);assert.ok(pet.removed);assert.equal(b.over?.won,false);assert.ok(!b.seenDeaths.includes(pet.id));});
test('facilities and zero HP relays cannot stand in for surviving combat units',()=>{const b=make([]),p=b.units[0];B.spawn(b,p,{name:'静态建筑',h:1,a:0,basis:'P',duration:99,facility:true});B.spawn(b,p,{name:'中继',h:.2,a:0,basis:'P',duration:99,relay:true});fallen(b);assert.equal(b.over.won,false);assert.match(b.over.reason,/全部退场/);});
test('sealed surviving ally is not declared dead',()=>{const b=make();b.units[1].sealedBy='coffin';fallen(b);assert.equal(b.over,null);});
test('revival remains effective before team defeat evaluation',()=>{const b=make([]),p=b.units[0];p.revives=1;fallen(b);assert.ok(p.hp>0);assert.equal(b.over,null);});
const career=()=>{const s=R.createRun({seed:'team-v22',node:'N01',iron:false});for(let i=0;i<11;i++)R.drawNext(s);R.enterNode(s,true);R.depart(s);R.beginBattle(s);s.battle.config.aiEvaluation=true;return s;};
test('posthumous victory awards growth and rescues player for the next encounter',()=>{const s=career(),b=s.battle;fallen(b);for(const e of b.units.filter(u=>u.side==='enemy'))e.hp=0;B.checkEnd(b);assert.equal(b.over.won,true);const r=R.settle(s);assert.ok(r.rescued);assert.equal(r.growth.length,5);assert.equal(s.hp,Math.floor(s.stats.H*.3));assert.notEqual(s.phase,'ending');R.continueGrowth(s);assert.equal(s.phase,'battle');assert.ok(s.battle.units[0].hp>0);});
test('standard journey ends on full team wipe and not on player exit alone',()=>{const s=career(),b=s.battle;fallen(b);assert.equal(b.over,null);for(const a of b.units.filter(u=>u.side==='ally'))a.hp=0;B.checkEnd(b);assert.equal(b.over.won,false);R.settle(s);assert.equal(s.phase,'ending');});
test('objective victory can be completed by survivors while player is down',()=>{const b=make();b.spec.id='N01-2';fallen(b);b.round=5;B.checkEnd(b);assert.equal(b.over.won,true);assert.equal(b.over.kind,'objective');});
test('stale dead player actor is released instead of blocking clock',()=>{const b=make();fallen(b);b.actor='player';B.advance(b);assert.notEqual(b.actor,'player');});
test('unsettled legacy player-death defeat resumes when allies remain',()=>{const s=career(),b=s.battle;fallen(b);b.over={won:false,kind:'defeat',reason:'你已倒下，行动终止'};R.validateSave(s);assert.equal(b.over,null);});
test('motion outcome data does not alter team victory results',()=>{const b=make(),c=structuredClone(b);b.config.aiEvaluation=false;b.config.skipIntents=true;b.config.aiPolicy='legacy';fallen(b);fallen(c);for(const z of [b,c]){const e=z.units.find(u=>u.side==='enemy'),a=z.units[1];e.hp=1;e.shields=[];z.actor=a.id;B.act(z,'martial',e.id);}delete b.visual;delete c.visual;delete b.config;delete c.config;for(const z of [b,c])for(const u of z.units)delete u.intent;assert.deepEqual(b,c);});

test('last allied self-destruct attack still wins if it kills the final enemy',()=>{const b=make([]),p=b.units[0],pet=B.spawn(b,p,{name:'敛傲测试',h:.4,a:4,basis:'P',v:100,duration:3,limit:1});pet.selfDestruct=true;fallen(b);const e=b.units.find(u=>u.side==='enemy');e.hp=1;e.shields=[];b.actor=pet.id;B.act(b,'martial',e.id);assert.ok(pet.removed);assert.equal(b.over?.won,true);});
