import test from 'node:test';import assert from 'node:assert/strict';import * as R from '../dist/run.js';import * as B from '../dist/battle.js';import {CARDS,actionFor} from '../dist/cards.js';import {derive,tierLabel} from '../dist/math.js';
const born=seed=>{let s=R.createRun({seed,node:'N01'});for(let i=0;i<11;i++)R.drawNext(s);R.enterNode(s,true);return s;};
test('defaults, final talent draw and art prototype are present',()=>{const s=born('v17');assert.equal(s.name,'博士');assert.equal(s.iron,true);assert.equal(s.rolls.length,11);assert.ok(s.rolls[4].name.includes('（'));assert.ok(s.talent);assert.ok(s.multiplier>0);assert.equal(s.days,20);assert.ok(!('injury'in s));assert.ok(!('manualAllies'in s));for(let i=0;i<17;i++)assert.ok(tierLabel(i).includes(' · '));});
test('all base and evolved A B have no cooldown and C has at most one',()=>{for(const c of CARDS)for(const m of [0,200])for(let i=0;i<3;i++){const a=actionFor(c,i,m);assert.equal(i<2?a.cd:Math.min(a.cd,c.id==='AK011'?2:1),a.cd,c.id+'/'+m+'/'+i);if(i<2)assert.equal(a.cd,0);}});
test('summons take independent initiative and owner does not grant a free attack',()=>{const b=B.newBattle({art:'AK098',mastery:200,stats:derive(Array(5).fill(3))},{id:'SIM',title:'test',allies:[],enemies:['heavy']},{config:{aiEvaluation:true}});let p=b.units[0],pet=b.units.find(u=>u.owner),enemy=b.units.find(u=>u.npcId==='heavy');b.actor=p.id;p.turn=1;const before=enemy.hp;B.act(b,'defend',p.id);assert.equal(enemy.hp,before);assert.equal(B.legal(b,pet,'martial'),null);b.actor=pet.id;pet.turn=1;B.act(b,'martial',enemy.id);assert.ok(enemy.hp<before);pet.gauge=100;B.advance(b);assert.equal(b.actor,pet.id);});
test('Mephisto has three distinct hosted roles with physical attacks',()=>{const s=R.createSandbox({enemy:'meph'}),b=R.beginBattle(s),pets=b.units.filter(u=>u.owner);assert.deepEqual(pets.map(u=>u.name),['宿主重装组长','宿主流浪者','狂暴宿主士兵']);assert.ok(pets.every(u=>u.stats.V>0&&u.attackType==='physical'));assert.ok(pets[0].stats.D>pets[1].stats.D);assert.ok(pets[2].attack>pets[1].attack);assert.ok(pets[0].regen>0&&pets[1].regen>0&&pets[2].selfBleed);});
test('vector defeat returns to preparation and cannot end ironman journey',()=>{let s;for(let i=0;i<100;i++){s=born('vector-'+i);R.train(s);if(s.phase==='vectorPrep')break;}assert.equal(s.phase,'vectorPrep');assert.equal(s.pendingTraining.enemyTier,undefined);R.drawVectorArt(s);R.drawVectorTier(s);assert.ok(s.pendingTraining.enemyTier<=Math.floor(s.stats.rating.score));let b=R.beginVector(s);b.units[0].hp=0;b.over={won:false,kind:'defeat',reason:'test'};const old=s.hp;R.settle(s);assert.equal(s.phase,'camp');assert.equal(s.hp,old);assert.equal(s.iron,true);assert.equal(s.days,19);assert.equal(s.dailyHistory.length,1);});
test('battle victory grows all axes and never refills supplies',()=>{const s=born('gain');R.depart(s);const b=R.beginBattle(s),supply=s.supply;b.over={won:true,kind:'victory',reason:'test'};R.settle(s);assert.equal(s.lastResult.growth.length,5);assert.ok(s.lastResult.growth.every(x=>Number.isFinite(x.actual)&&x.mult===s.multiplier));assert.equal(s.supply,supply);});
test('legend pool probability increases using the same seed sample',()=>{let n=0,l=0;for(let i=0;i<2000;i++){for(const legend of [false,true]){let s=R.createRun({seed:'legend-'+i,legend});for(let j=0;j<5;j++)R.drawNext(s);if(s.rolls[4].pool==='hidden')legend?l++:n++;}}assert.ok(n>=60&&n<145);assert.ok(l>520&&l<690);});
