import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {CARDS,BY_ID,actionFor,evolvedCard} from '../dist/cards.js';import * as R from '../dist/run.js';import * as B from '../dist/battle.js';import {derive,WEIGHTS,energyRegen,restEnergy} from '../dist/math.js';
const born=seed=>{const s=R.createRun({seed,node:'N01'});for(let i=0;i<11;i++)R.drawNext(s);R.enterNode(s,true);return s;};
test('initial weights reduce D to 28 percent and keep higher ranks increasingly rare',()=>{assert.ok(Math.abs(WEIGHTS.reduce((a,b)=>a+b)-100)<1e-6);assert.equal(WEIGHTS.slice(0,3).reduce((a,b)=>a+b),28);for(let i=5;i<17;i++)assert.ok(WEIGHTS[i]>WEIGHTS[i+1]||i===16);});
test('low-end energy supports repeated casts and recovery scales with capacity',()=>{for(let tier=0;tier<17;tier++){const s=derive(Array(5).fill(tier));assert.ok(s.Emax>=163);assert.ok(energyRegen(s.Emax)>=12);assert.ok(restEnergy(s.Emax)>=32);}const s=derive(Array(5).fill(3));assert.equal(s.Emax,200);assert.equal(energyRegen(s.Emax),12);assert.equal(restEnergy(s.Emax),32);});
function checkUpgrade(old,now,id){assert.equal(now.op,old.op,id);for(const k of ['coef','perResource','scalesResource','perArmor','perGauge','power'])if(typeof old[k]==='number')assert.ok((now[k]??1)>=old[k]-1e-8,id+'/'+k);for(const k of ['effects','otherwise','fallback'])if(old[k])old[k].forEach((o,i)=>checkUpgrade(o,now[k][i],id));}
test('all 181 automatic mastery upgrades preserve base effects and never raise cost',()=>{for(const c of CARDS){for(let i=0;i<3;i++){const zero=actionFor(c,i,0),m100=actionFor(c,i,100),m200=actionFor(c,i,200);assert.ok(m100.cost<=zero.cost,c.id);assert.ok(m200.cost<=m100.cost,c.id);assert.ok(m200.cd<=m100.cd,c.id);zero.ops.forEach((o,j)=>checkUpgrade(o,m100.ops[j],c.id));if(!c.ascendOps)zero.ops.forEach((o,j)=>checkUpgrade(o,m200.ops[j],c.id));}const v=evolvedCard(c,200);assert.ok(v.cap>=c.cap,c.id+'/cap');assert.ok(v.initial>=c.initial,c.id+'/initial');}});
test('legacy selected specializations and extremes cannot impose energy or turn penalties',()=>{const stats=derive(Array(5).fill(4)),s={id:'test',title:'test',allies:[],enemies:['heavy']};const a=B.newBattle({art:'AK018',stats,mastery:200},s,{config:{aiEvaluation:true}}),b=B.newBattle({art:'AK018',stats,mastery:200,specialization:'A',extreme:true},s,{config:{aiEvaluation:true}});for(const k of ['A','B','C'])assert.deepEqual(B.skill(a.units[0],k),B.skill(b.units[0],k));});
test('Logos decisive arts damage three targets and protect allies',()=>{const stats=derive(Array(5).fill(5)),b=B.newBattle({art:'AK018',stats,mastery:200},{id:'test',title:'test',allies:[],enemies:['heavy','heavy','heavy','heavy']},{config:{aiEvaluation:true}}),p=b.units[0],es=b.units.filter(u=>u.side==='enemy');for(const e of es){e.stats.H=e.hp=10000;e.gauge=80;}p.turn=4;b.actor=p.id;const hp=es.map(e=>e.hp),a=B.skill(p,'C');assert.equal(a.target,'enemy_up_to_three');assert.equal(a.ops[0].coef,4.32);B.act(b,'C',es[0].id);assert.equal(es.filter((e,i)=>e.hp<hp[i]).length,3);assert.ok(B.shields(p)>0);assert.ok(es.slice(0,3).every(e=>e.gauge===20));});
test('victory growth is persisted, rewards deduplicated, acknowledgement enters the next battle',()=>{const s=born('growth-v20');s.mastery=99;R.depart(s);const b=R.beginBattle(s);b.over={won:true,kind:'victory',reason:'test'};const r=R.settle(s);assert.equal(r.before.mastery,99);assert.ok(r.after.mastery>=100);assert.equal(s.pendingGrowth,r);for(const k of ['H','D','A','P','R','Emax'])assert.ok(r.after.stats[k]>=r.before.stats[k]);assert.ok(r.mastery<=10);const loaded=structuredClone(s);R.validateSave(loaded);assert.deepEqual(loaded.pendingGrowth,r);R.continueGrowth(s);assert.equal(s.phase,'battle');assert.equal(s.battle.spec.id,'N01-2');assert.equal(s.pendingGrowth,undefined);const rerun=born('dedupe-v20');R.depart(rerun);let bb=R.beginBattle(rerun);bb.over={won:true,kind:'victory',reason:'test'};R.settle(rerun);const m=rerun.mastery;rerun.phase='battle';R.settle(rerun);assert.equal(rerun.mastery,m);assert.equal(rerun.lastResult.mastery,0);assert.equal(rerun.lastResult.growth.length,0);});
test('old saves preserve progress and energy ratio when capacities migrate',()=>{const s=born('migrate-v20');s.version=2;s.mastery=150;R.depart(s);R.beginBattle(s);const p=s.battle.units[0];p.stats.Emax=100;p.e=25;s.specialization='A';s.extreme=true;R.validateSave(s);assert.equal(s.version,3);assert.equal(s.mastery,150);assert.equal(s.specialization,'');assert.equal(s.extreme,false);assert.equal(p.e,Math.floor(p.stats.Emax*.25));});
test('protected user-defined modes retain targeting, effects and resource counts',()=>{const baseline=JSON.parse(fs.readFileSync(new URL('./fixtures/v19-protected.json',import.meta.url)));const ids=['AK002','AK010','AK013','AK019','AK027','AK030','AK035','AK040','AK043','AK053','AK086','AK087','AK093','AK098','AK108','AK123','AK179','AK183','AK184','AK185','AK208'];function modes(ops){return ops.map(o=>{const n={...o};for(const k of ['coef','perResource','scalesResource','perArmor','perGauge','power'])delete n[k];for(const k of ['effects','otherwise','fallback'])if(n[k])n[k]=modes(n[k]);return n;});}for(const id of ids){const old=baseline.find(row=>row.card.id===id);const c=BY_ID[id];for(let i=0;i<3;i++){assert.equal(c.actions[i].target,old.card.actions[i].target,id+'/'+i);assert.deepEqual(modes(c.actions[i].ops),modes(old.card.actions[i].ops),id+'/'+i);}if(c.ascendOps)assert.deepEqual(modes(c.ascendOps.flat()),modes(old.card.ascendOps.flat()),id);}});

test('talent only affects numerical axes, never mastery income or ascension strength',()=>{let seed;for(let i=0;i<100;i++){const s=born('talent-independent-'+i),r=R.train(s);if(r.mastery){seed='talent-independent-'+i;break;}}assert.ok(seed);const slow=born(seed),fast=structuredClone(slow);slow.multiplier=.5;fast.multiplier=2.1;const a=R.train(slow),c=R.train(fast);assert.equal(a.mastery,c.mastery);assert.ok(c.gains[0].actual>a.gains[0].actual);let s;for(let i=0;i<100;i++){s=born('talent-vector-'+i);R.train(s);if(s.phase==='vectorPrep')break;}const one=structuredClone(s),two=structuredClone(s);one.multiplier=.5;two.multiplier=2.1;for(const r of [one,two]){const b=R.beginVector(r);b.over={won:true,kind:'victory',reason:'test'};R.settle(r);}assert.equal(one.mastery,two.mastery);});

test('NPC finished profiles do not receive player specialization multipliers',()=>{const b=B.newBattle({art:'AK018',stats:derive(Array(5).fill(4)),mastery:200},{id:'test',title:'test',allies:['logos'],enemies:['heavy']},{config:{aiEvaluation:true}}),npc=b.units.find(u=>u.npcId==='logos');assert.equal(B.skill(npc,'C').ops[0].coef,3.6);assert.equal(B.skill(b.units[0],'C').ops[0].coef,4.32);});
test('battle-only maximum health traits never compound across victories',()=>{for(const art of ['AK123','AK141']){const s=born('hp-v20');s.art=art;s.mastery=200;R.depart(s);let b=R.beginBattle(s),p=b.units[0],ratio=p.stats.H/s.stats.H;p.hp=Math.floor(p.stats.H*.7);b.over={won:true,kind:'victory',reason:'test'};R.settle(s);assert.ok(s.hp/s.stats.H>.69&&s.hp/s.stats.H<.71);R.continueGrowth(s);p=s.battle.units[0];assert.ok(p.hp<=p.stats.H);assert.ok(Math.abs(p.stats.H/s.stats.H-ratio)<.01);}});
