import test from 'node:test';import assert from 'node:assert/strict';
import {CARDS,BY_ID,actionFor,actionText} from '../dist/cards.js';import * as B from '../dist/battle.js';import {derive} from '../dist/math.js';import {MEMES} from '../dist/motion.js';
const make=(art,enemyCount=3)=>{const b=B.newBattle({art,stats:derive(Array(5).fill(4)),mastery:200},{id:'test',title:'联动测试',allies:['amiya'],enemies:Array(enemyCount).fill('heavy')},{rng:571,config:{aiEvaluation:true,skipIntents:true}});for(const t of b.units.filter(v=>v.side==='enemy'))t.hp=t.stats.H=100000;b.round=4;return b;};
const prime=b=>{let p=b.units[0];p.turn=4;p.e=p.stats.Emax;p.cd.C=0;b.actor=p.id;return p;};
const cast=(b,k,id)=>{const p=prime(b);B.act(b,k,id||B.targets(b,p,B.skill(p,k))[0]?.id);return p;};
test('all 182 arts have readable rounded descriptions at all mastery levels',()=>{assert.equal(CARDS.length,182);for(const c of CARDS)for(const m of [0,100,200])for(let i=0;i<3;i++){const text=actionText(actionFor(c,i,m));assert.ok(!/\d+\.\d{3,}/.test(text),c.id+text);assert.ok(!/undefined|NaN/.test(text),c.id);}});
test('meteor is delayed and gains one resource once across all targets',()=>{const b=make('AK006'),p=prime(b);p.res=1;const hp=b.units.filter(v=>v.side==='enemy').map(v=>v.hp);B.act(b,'C',b.units[2].id);assert.equal(p.res,1);const es=b.units.filter(v=>v.side==='enemy');assert.deepEqual(es.map(v=>v.hp),hp);assert.ok(es.every(v=>Object.keys(v.statuses).some(k=>k.includes('陨石'))));b.actor=null;p.gauge=0;for(const v of es)v.gauge=100;B.advance(b);assert.ok(es[0].hp<hp[0]);assert.equal(B.stacks(es[0],'破魔'),2);});
test('witch random debuffs work without preexisting statuses and replay identically',()=>{const b=make('AK009'),c=structuredClone(b);cast(b,'C');cast(c,'C');assert.deepEqual(b,c);const es=b.units.filter(v=>v.side==='enemy');assert.equal(Object.keys(es[0].statuses).length,3);assert.equal(Object.keys(es[1].statuses).length,3);assert.equal(Object.keys(es[2].statuses).length,0);});
test('flow copies ally panel, B preserves sample attributes and C creates four acting clones',()=>{const b=make('AK011'),p=cast(b,'A',b.units[1].id),sample=b.units[1],flow=b.units.find(v=>v.owner===p.id);for(const k of ['A','P','D','R'])assert.equal(flow.stats[k],sample.stats[k]*.65);assert.equal(flow.stats.H,Math.floor(sample.stats.H*.65));const stats=structuredClone(flow.stats);cast(b,'B');assert.deepEqual(flow.stats,stats);cast(b,'C');let clones=b.units.filter(v=>v.tempFlow&&!v.removed);assert.equal(clones.length,4);assert.ok(clones.every(v=>v.gauge===100&&v.attackType===flow.attackType));assert.equal(B.skill(p,'C').cd,2);assert.equal(B.legal(b,p,'C'),'冷却中');b.actor=null;const es=b.units.filter(v=>v.side==='enemy'),hp=es[0].hp;for(let i=0;i<4;i++){B.advance(b);const u=b.units.find(v=>v.id===b.actor);assert.ok(u.tempFlow);B.act(b,'martial',es[0].id);}assert.ok(es[0].hp<hp);b.time=100;B.advance(b);assert.ok(clones.every(v=>v.removed));assert.ok(B.alive(flow));assert.equal(b.seenDeaths.length,0);});
test('ifrit all attacks hit all enemies and C refreshes soil for B without enemy energy refund',()=>{const b=make('AK012'),es=b.units.filter(v=>v.side==='enemy');cast(b,'A');assert.ok(es.every(v=>B.has(v,'焦土')&&B.has(v,'灼烧')));const before=es.map(v=>v.e);cast(b,'C');assert.ok(es.every(v=>B.has(v,'焦土封锁')&&B.has(v,'焦土')));assert.deepEqual(es.map(v=>v.e),before);cast(b,'B');assert.ok(es.every(v=>!B.has(v,'焦土')&&!B.has(v,'灼烧')));});
test('clock snapshots gauge before its reduction and harms enemy before its intent',()=>{const b=make('AK014'),es=b.units.filter(v=>v.side==='enemy');es[0].gauge=90;es[1].gauge=10;cast(b,'C');const s0=Object.values(es[0].statuses).find(s=>s.event==='start'),s1=Object.values(es[1].statuses).find(s=>s.event==='start');assert.ok(s0.effects[0].coef>s1.effects[0].coef);assert.equal(es[0].gauge,30);assert.equal(es[1].gauge,0);});
test('paralysis clears even a ready gauge rather than subtracting sixty',()=>{const b=make('AK029'),t=b.units.find(v=>v.side==='enemy');t.gauge=165;cast(b,'A',t.id);cast(b,'B',t.id);assert.equal(t.gauge,0);assert.ok(!B.has(t,'麻痹'));});
test('Fiammetta gains only one calibration per AoE and B uses it on every victim',()=>{const b=make('AK095'),p=cast(b,'A');assert.equal(p.res,1);cast(b,'A');assert.equal(p.res,2);const es=b.units.filter(v=>v.side==='enemy'),hp=es.map(v=>v.hp);cast(b,'B');assert.equal(p.res,0);assert.ok(es.every((v,i)=>v.hp<hp[i]));assert.ok(es.every((v,i)=>hp[i]-v.hp===hp[0]-es[0].hp));});
test('Typhon final C is exactly 799 percent and its meme targets her C',()=>{assert.equal(actionFor(BY_ID.AK097,2,200).ops[0].coef,7.99);assert.equal(MEMES.AK097.button,'C');});
test('Kristen raised C remains star-gated and grants half HP shield and 24 energy',()=>{const b=make('AK195'),p=prime(b),a=b.units[1];assert.equal(B.legal(b,p,'C'),'专属资源不足');p.res=1;a.e=0;B.act(b,'C',b.units[2].id,{ally:a.id});assert.equal(p.res,0);assert.equal(B.shields(a),Math.floor(a.stats.H*.5));assert.equal(a.e,24);});
test('country execution is gated by global round, mark and one use; revives still run',()=>{const b=make('AK215'),p=prime(b),t=b.units.find(v=>v.side==='enemy');b.round=3;p.turn=30;assert.equal(B.legal(b,p,'C'),'第4战场轮起可用');b.round=4;assert.equal(B.legal(b,p,'C'),'没有合法目标');cast(b,'A',t.id);assert.equal(t.statuses['国度迟滞'].values.V,-.5);t.shields=[{hp:1e8,until:99}];t.statuses['锁血']={n:1,until:99};t.revives=1;cast(b,'C',t.id);assert.equal(t.revives,0);assert.ok(t.hp>0);p.cd.C=0;b.actor=p.id;assert.equal(B.legal(b,p,'C'),'本场次数已用尽');});
test('invalid country execution target does not consume energy or limit',()=>{const b=make('AK215'),p=prime(b),es=b.units.filter(v=>v.side==='enemy');cast(b,'A',es[0].id);prime(b);const e=p.e;assert.throws(()=>B.act(b,'C',es[1].id),/目标不可选/);assert.equal(p.e,e);assert.equal(p.used.C,undefined);});
test('Shuo is separate from Chongyue, its blades self destroy, body protects and death ends protection',()=>{assert.equal(BY_ID.AK150.source,'重岳');const b=make('AK221'),p=cast(b,'A');cast(b,'B');const ps=b.units.filter(v=>v.name==='敛傲');assert.equal(ps.length,2);const t=b.units.find(v=>v.side==='enemy');b.actor=ps[0].id;B.act(b,'martial',t.id);assert.ok(ps[0].removed);assert.ok(!b.seenDeaths.includes(ps[0].id));cast(b,'C',t.id);assert.ok(t.removed&&!t.deadOnce);const body=b.units.find(v=>v.shuoBody);const hp=p.hp;B.damage(b,b.units.find(v=>v.side==='enemy'&&!v.removed),p,10000,'true',100,{indirect:true});assert.equal(p.hp,hp);body.removed=true;B.damage(b,b.units.find(v=>v.side==='enemy'&&!v.removed),p,100,'true',100,{indirect:true,ignoreShield:true});assert.equal(p.hp,hp-100);});
test('animation event is optional and combat outcomes stay deterministic',()=>{const b=make('AK012'),c=structuredClone(b);b.config.aiEvaluation=false;b.config.skipIntents=true;b.config.aiPolicy='legacy';cast(b,'A');cast(c,'A');delete b.visual;delete b.config;delete c.config;for(const u of b.units)delete u.intent;for(const u of c.units)delete u.intent;assert.deepEqual(b,c);});
test('forced exit releases a coffin captive without firing death or revival rewards',()=>{const b=make('AK221'),p=prime(b),jailer=b.units.find(v=>v.side==='enemy'),captive=b.units[1],coffin=B.spawn(b,jailer,{name:'黑棺',h:.2,a:0,basis:'P',limit:1,duration:2,facility:true});coffin.sealed=captive.id;coffin.coffinOwner=jailer.id;captive.sealedBy=coffin.id;jailer.revives=1;B.retire(b,jailer);assert.ok(jailer.removed);assert.equal(jailer.revives,1);assert.equal(captive.sealedBy,undefined);assert.ok(coffin.removed);assert.ok(!b.seenDeaths.includes(jailer.id));});

test('paralysis gauge clearing notifies reactive effects once',()=>{const b=make('AK029'),p=prime(b),t=b.units.find(v=>v.side==='enemy');t.gauge=165;t.e=0;t.statuses['测试中继']={event:'gaugeLoss',src:t.id,until:99,effects:[{op:'energy',to:'self',n:7}]};cast(b,'A',t.id);cast(b,'B',t.id);assert.equal(t.gauge,0);assert.equal(t.statuses['测试中继'],undefined);assert.ok(t.e>0);});


