import fs from 'node:fs';
import {rollStat,derive,seedNumber,random} from '../dist/math.js';
import * as B from '../dist/battle.js';
import {hit} from '../dist/cards.js';
fs.mkdirSync(new URL('../artifacts/',import.meta.url),{recursive:true});
const card={id:'npc:white',passive:[],actions:[{button:'A',name:'白板源石技艺',cost:14,cd:0,unlock:0,target:'enemy_one',ops:[hit(1)]}]};
const rng={rng:seedNumber('independent-20261001')},samples=[[],[],[]];let draws=0;
while(samples.some(s=>s.length<1000)&&draws<500000){draws++;let x=Array.from({length:5},()=>rollStat(rng)),y=Array.from({length:5},()=>rollStat(rng));let sx=derive(x),sy=derive(y);if(sx.rating.score>sy.rating.score)[sx,sy]=[sy,sx];let gap=Math.floor(sy.rating.score)-Math.floor(sx.rating.score),k=gap===1?0:gap===2?1:gap>=3?2:-1;if(k>=0&&samples[k].length<1000)samples[k].push([sx,sy]);}
function duel(pair,strategy,first){let [lo,hi]=pair.map(s=>({...s,H:Math.floor(s.H/1.1)}));let b=B.newBattle({art:'AK019',stats:lo,mastery:0},{id:'white',title:'白板',allies:[],enemies:[],goal:'全歼'},{rng:32,config:{aiEvaluation:true}});b.units[0].cardData=card;b.units.push(B.makeUnit('higher','高阶','enemy',hi,card));b.units[0].gauge=first==='lower'?1:0;b.units[1].gauge=first==='higher'?1:0;b.scene.limit=120;
for(let i=0;i<700&&!b.over;i++){B.advance(b);if(b.over)break;let u=b.units.find(v=>v.id===b.actor),t=B.foes(b,u)[0],phys=u.stats.A*(1-t.stats.D/(t.stats.D+4*u.stats.A)),magic=u.stats.P*(1-t.stats.R/(t.stats.R+4*u.stats.P)),choice=magic>phys&&!B.legal(b,u,'A')?'A':'martial';let strat=u.isPlayer?strategy:'adaptive';if(strat==='rest'&&u.hp/u.stats.H<.55&&u.lastAction!=='rest'||strat==='adaptive'&&u.hp/u.stats.H<.32&&u.lastAction!=='rest')choice='rest';if(strat==='defend'&&u.turn%3===1)choice='defend';if(strat==='physical')choice='martial';if(strat==='magic')choice=!B.legal(b,u,'A')?'A':'rest';B.act(b,choice,['rest','defend'].includes(choice)?u.id:t.id);}if(!b.over)throw Error('unresolved');return b.over.won;}
let results=samples.map((pairs,k)=>{let wins=0;for(let pair of pairs){let win=false;for(let first of ['lower','higher'])for(let strategy of ['attack','rest','defend','adaptive','physical','magic'])if(duel(pair,strategy,first)){win=true;break;}wins+=Number(win);}let n=pairs.length,p=wins/n,z=1.645,upper=(p+z*z/(2*n)+z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n)))/(1+z*z/n);return{gap:k===2?'3+':k+1,n,wins,rate:p,upper95:upper,pass:k===0||upper<=.05};});let report={at:new Date().toISOString(),draws,method:'独立五轴转盘；综合评级分层；双方先手；低阶六策略择优，高阶自适应攻击；100%P；无跨级伤害修正',results};fs.writeFileSync(new URL('../artifacts/independent-balance.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(results.some(r=>!r.pass))process.exitCode=1;

