import fs from 'node:fs';import path from 'node:path';import {DATA} from '../dist/data.js';import {CARDS,actionFor,actionText,evolvedCard,STATUS_INFO} from '../dist/cards.js';import {TIERS,ANCHORS,WEIGHTS} from '../dist/math.js';
const out=path.resolve('../outputs');let raw=new Map(DATA.arts.cards.map(c=>[c.art_id,c]));const review=c=>['敌方单位','传奇隐藏候选'].includes(raw.get(c.id).source_rarity)||raw.get(c.id).name_review==='review_required';const rows=CARDS.map(c=>({...c,name_review:review(c)?(raw.get(c.id).name_review==='user_specified_name'?'user_specified':'review_required'):'source_name_retained',source_rarity:raw.get(c.id).source_rarity,mastery_0:c.actions.map((_,i)=>{let a=actionFor(c,i,0);return{...a,effect_text:actionText(a)};}),mastery_200:evolvedCard(c,200).actions.map((_,i)=>{let a=actionFor(c,i,200);return{...a,effect_text:actionText(a)};})}));
fs.writeFileSync(path.join(out,'源石技艺_可执行卡表_v16.json'),JSON.stringify({version:16,runtime:true,count:181,normal:151,hidden:30,mastery_thresholds:[100,200],cards:rows},null,2));
let text='# 源石技艺 · 可执行卡表 v16\n\n181项：普通151、隐藏30。数值为本作回合制改编；原型名、操作标签和原创数值分开标注。H/A/P/D/R/E分别是最大生命、体术、术强、防御、魔抗、技力；Q=max(A,P)。基础E按操控20折为90%并向上取整。\n\nM0有A/B，M100可选专精：所选A或B基础E−3，另一招+2。M200解锁升变C；有异格映射时整组招式改为强化异格。极式C基础E+8、CD+1、直接伤害系数+20%、第4自身机会起、全场1次。\n\n';
function section(title,cards){text+='## '+title+'\n\n';for(let c of cards){text+=`### ${c.id} ${c.source} · ${c.name}\n\n- 池：${c.pool==='hidden'?'隐藏':'普通'}；[原型资料](${c.url})\n- 名称：${c.name_review==='source_name_retained'?'沿用原型':c.name_review==='user_specified'?'用户已指定，备查':'提交审阅；此处为可替换候选名'}。\n`;if(c.resource)text+=`- 专属资源：${c.resource}，初始${c.initial}，上限${c.cap}${c.ammo?'；自然+1、休整+2、实际击杀+2':''}。\n`;for(let t of c.passiveText||[])text+='- 特性：'+t+'\n';for(let a of c.mastery_0)text+=`\n**${a.button} · ${a.name}〔操作：${a.label}〕**　${a.cost}基础E / CD${a.cd} / ${a.target}${a.button==='C'?' / M200':''}\n\n${a.effect_text}\n`;if(c.ascend||c.variant||JSON.stringify(c.mastery_0.map(a=>a.ops))!==JSON.stringify(c.mastery_200.map(a=>a.ops))){text+='\n**M200升变：'+(c.ascend||'强化招式')+'**\n';let e=evolvedCard(c,200);if(e.resource)text+=`\n升变资源：${e.resource}，初始${e.initial}，上限${e.cap}；${e.ammoRecovery?'自然+'+e.ammoRecovery.natural+'、休整+'+e.ammoRecovery.rest+'、击杀+'+e.ammoRecovery.kill:'保持本卡明示恢复规则'}。\n`;for(let t of e.passiveText||[])text+='\n升变特性：'+t+'\n';for(let a of c.mastery_200)text+=`\n${a.button} · ${a.name}〔${a.label}〕：${a.cost}E / CD${a.cd}；${a.effect_text}\n`;}text+='\n';}}
section('一、无需再次审阅的原型名称',rows.filter(c=>!review(c)));section('二、集中名称审阅与用户指定名备查',rows.filter(c=>review(c)));
text+='## 通用状态与召唤规则\n\n';for(let [k,v]of Object.entries(STATUS_INFO))text+=`- **${k}**：${v}\n`;text+='\n召唤物默认继承主人100%D/R，攻击值在部署时快照，行动速度0；主人每次完成行动后攻击1次，新部署当次不攻击。只有明示设施不普攻。全场作战实体上限13，设施独立计数；超额部署失败仍消耗本次施法成本。召唤物被主人真实死亡或强制退场移除。\n';fs.writeFileSync(path.join(out,'源石技艺_完整文本与集中审阅_v16.md'),text);
let wheel='# 战力与成长 · 实装 v16\n\n五项独立抽取，不根据对手分级修正伤害。每档初值在级分前20%内均匀抽取，为后续成长保留空间；档内按相邻锚点几何插值。下表为各档起点、未施加感染身份。\n\n| 分级 | 概率 | 耐受/防御/体术/术强/适应性锚点 | 基础H | E上限 |\n|---|---:|---:|---:|---:|\n';TIERS.forEach((n,i)=>wheel+=`| ${n} | ${WEIGHTS[i]}% | ${ANCHORS[i]} | ${12*ANCHORS[i]} | ${Math.floor(40+60*Math.sqrt(ANCHORS[i]/100))} |\n`);wheel+='\n感染者H×0.9、P×1.15；非感染者H×1.1。出生地、种族没有额外效果。角色档案展示基础指标，战斗面板和综合评级包含身份修正。\n\n综合级分=25%耐受+15%强度+20%适应性+30%较高攻击项+10%较低攻击项，最多为中位项+2；王庭以上还需要至少3项达到该级分。训练增长后实时重算。王庭/神明/崛起训练效率为15%/4%/1%；跨入10至16级分需8/12/18/24/32/42/56同水平实战凭证，待突破积累最多0.25级分。\n\n## 成长天赋\n\n';for(let g of DATA.talents.grades)wheel+=`- ${g.grade}：概率${g.weight}%，训练/修行×${g.training_multiplier}；不增加初始属性。\n`;wheel+='\n## 日程与战役\n\n每天1项：能力锻炼、技艺修行、医疗或后勤；日终回血10%H。训练转盘40%主项+.04、25%+.07、10%+.12、15%主项+.04辅项+.02、5%全项+.015、5%最低项+.02并回血30%H。修行40%+18M、30%+24M、20%+30M、10%+40M，乘资质后取整。\n\n';for(let n of DATA.campaign.nodes)wheel+=`- ${n.id} ${n.name}：独立开局${n.prep_days}日，4场作战，建议${TIERS[n.recommended_score[0]]}起。\n`;wheel+='\n连贯战役节点之间准备日为2/1/0/0/0/21/4/2/1/0/0，从N01起总计41日。战间急救2补给回25%全队H；野战护理4补给回75%H并清1伤势，两者共享1次额度、不复活。标准模式一次节点重试需要预留1准备日与3补给；撤离和Boss击杀分开记账。\n';fs.writeFileSync(path.join(out,'战力成长与战役实装_v16.md'),wheel);
console.log(JSON.stringify({cards:rows.length,withoutReview:rows.filter(c=>!review(c)).length,review:rows.filter(review).length}));
