import fs from 'node:fs';import path from 'node:path';import {DATA} from '../dist/data.js';import {CARDS,actionText,evolvedCard,STATUS_INFO,npcCard} from '../dist/cards.js';import * as B from '../dist/battle.js';import {TIERS,ANCHORS,WEIGHTS,tierLabel,numericRating,derive} from '../dist/math.js';import {DAILY_PROJECTS,TRANSITION} from '../dist/run.js';import {narrative,mission} from '../dist/briefings.js';
const out=path.resolve('../outputs');fs.mkdirSync(out,{recursive:true});const write=(n,s)=>fs.writeFileSync(path.join(out,n+'_v17.md'),s);const raw=new Map(DATA.arts.cards.map(c=>[c.art_id,c]));const review=c=>['敌方单位','传奇隐藏候选'].includes(raw.get(c.id)?.source_rarity)||raw.get(c.id)?.name_review==='review_required';
const cn=s=>String(s).replace(/([0-9.%＋+−×()（）/]+)Q/g,'$1较高攻击强度').replace(/([0-9.%＋+−×()（）/]+)H/g,'$1最大生命').replace(/([0-9.%＋+−×()（）/]+)A/g,'$1体术强度').replace(/([0-9.%＋+−×()（）/]+)P/g,'$1技艺强度').replace(/([0-9.%＋+−×()（）/]+)D/g,'$1防御').replace(/([0-9.%＋+−×()（）/]+)R/g,'$1魔抗').replace(/\bHP\b/g,'生命');
const actions=(c,m)=>{const u=B.makeUnit('export',c.source,'ally',derive([4,4,4,4,4]),c,{mastery:m});return ['A','B','C'].map(k=>B.skill(u,k)).filter(Boolean).map(a=>({...a,actual_energy:B.cost(u,a),effect_text:cn(actionText(a))}));};
const rows=CARDS.map(c=>({...c,name_review:review(c)?(raw.get(c.id)?.name_review==='user_specified_name'?'user_specified':'review_required'):'source_name_retained',source_rarity:raw.get(c.id)?.source_rarity,mastery_0:actions(c,0),mastery_200:actions(c,200),evolved_passives:evolvedCard(c,200).passiveText}));
fs.writeFileSync(path.join(out,'源石技艺_可执行卡表_v17.json'),JSON.stringify({version:17,count:181,normal:151,hidden:30,mastery_thresholds:[100,200],cards:rows},null,2));
let arts='# 源石技艺 · 可执行卡表 v17\n\n181项：普通151、隐藏30。所有倍率为本作改编，原型资料不等于官方回合制规则。名称按要求先列无需审阅部分，再集中列候选名与用户已指定名。E表示技力，较高攻击强度=max(体术强度,技艺强度)。\n\n所有A/B无冷却；较强C最多冷却1次自身行动机会。M100解锁A或B专精：该招基础费用−3、另一招+2；M200解锁升变C。异格映射会替换整组招式。极式：C伤害系数×1.2、基础费用+8、冷却1次、自身第4次行动起可用、每场一次。下列实际E为无专精、无临时加减费的基础费用×0.9向上取整；游戏按钮显示本次实际费用。\n\n';
for(const [title,list]of [['一、无需再次审阅的原型名称',rows.filter(c=>!review(c))],['二、集中名称审阅与用户指定名备查',rows.filter(review)]]){arts+='## '+title+'\n\n';for(const c of list){arts+=`### ${c.id} ${c.name}（${c.source}）\n\n- 池：${c.pool==='hidden'?'隐藏':'普通'}；[原型资料](${c.url})。\n- 名称：${c.name_review==='source_name_retained'?'沿用原型':c.name_review==='user_specified'?'用户已指定，备查':'候选名称，提交审阅'}。\n`;if(c.resource)arts+=`- 专属资源：${c.resource}，初始${c.initial}，上限${c.cap}。${c.ammo?'弹药自然/休整/击杀补充按卡片资源规则执行。':''}\n`;for(const t of c.passiveText||[])arts+='- 特性：'+cn(t)+'\n';for(const a of c.mastery_0)arts+=`\n**${a.button} · ${a.label||a.name}**：${a.actual_energy} E（基础${a.cost}）；冷却${a.cd}${a.button==='C'?'；M200解锁':''}。\n\n${a.effect_text}\n`;if(c.ascend||c.variant||JSON.stringify(c.mastery_0)!==JSON.stringify(c.mastery_200)){const e=evolvedCard(c,200);arts+=`\n**M200升变：${c.ascend||'强化招式'}**\n\n`;if(e.resource)arts+=`资源：${e.resource}，初始${e.initial}，上限${e.cap}。${e.ammoRecovery?'自然+'+e.ammoRecovery.natural+' / 休整+'+e.ammoRecovery.rest+' / 击杀+'+e.ammoRecovery.kill+'。':''}\n`;for(const t of e.passiveText||[])arts+='\n'+cn(t)+'\n';for(const a of c.mastery_200)arts+=`\n${a.button} · ${a.label||a.name}：${a.actual_energy} E / 冷却${a.cd}；${a.effect_text}\n`;}arts+='\n';}}
arts+='## 通用状态与召唤\n\n';for(const[k,v]of Object.entries(STATUS_INFO))arts+=`- **${k}**：${cn(v)}\n`;arts+='\n召唤物进入阵列并按自身速度独立行动。主人行动不会免费触发所有召唤物普攻；明示指令可额外攻击。召唤攻击、防御、魔抗在部署时快照。持续时间按主人行动机会计，设施与中继无普通行动；辅助召唤物在自身行动结束补充明示支援。主体实体上限13，设施独立计数；主人实际死亡/强制退场移除其召唤物。所有召唤比例与评级见《剧情单位_完整数值与招式》。\n';write('源石技艺_完整文本与集中审阅',arts);
const audit=JSON.parse(fs.readFileSync('artifacts/v17/content-audit.json'));let units='# 剧情单位与召唤物 · v17\n\n所有剧情单位先以生理耐受=生命上限÷12、物理强度=防御、战斗技巧=体术强度、技艺强度、适应性=魔抗反推级分，再使用同一综合公式。56名单位原有故事档与实际面板复核，没有整档错位；界面右上角采用实际面板评级。\n\n';
const nr=DATA.campaign.units.map(raw=>{const c=npcCard(raw),a=actions(c,200);return {...raw,verified_rating:numericRating(raw.stats),actions:a};});fs.writeFileSync(path.join(out,'剧情单位_完整数值与招式_v17.json'),JSON.stringify({version:17,units:nr,summons:audit.summons},null,2));
for(const u of nr){units+=`## ${u.name} · ${u.verified_rating.name}\n\n| 生命 | 防御 | 体术 | 技艺 | 魔抗 | 技力 | 速度 |\n|---:|---:|---:|---:|---:|---:|---:|\n| ${u.stats.H} | ${u.stats.D} | ${u.stats.A} | ${u.stats.P} | ${u.stats.R} | ${u.stats.Emax} | ${u.stats.V} |\n\n`;for(const a of u.actions)units+=`- **${a.button} · ${a.label||a.name}**：${a.actual_energy} E，冷却${a.cd}；${a.effect_text}\n`;}
units+='## 召唤物面板核对\n\n以下为同档主人测试快照，比例以部署时主人属性计算；攻击比例分母为主人较高攻击项，具体体术/技艺取值见卡表。每个原型、名称与部署动作分别列出，避免混淆同名设施。\n\n| 原型 | 部署 | 名称 | 生命比例 | 攻击/较高攻击 | 防御比例 | 魔抗比例 | 速度 | 伤害类型 |\n|---|---|---|---:|---:|---:|---:|---:|---|\n';for(const s of audit.summons)units+=`| ${s.art} | ${s.button} | ${s.name} | ${(100*s.healthRatio).toFixed(1)}% | ${(100*s.attackRatio).toFixed(1)}% | ${(100*s.defenseRatio).toFixed(1)}% | ${(100*s.resistanceRatio).toFixed(1)}% | ${s.speed} | ${s.attackType||'设施/中继'} |\n`;
units+='\n梅菲斯特初始三宿主：重装95%生命、65%较高攻击、150%防御、40%魔抗、速度70、嘲讽、每自身机会回复4%生命；流浪者80%生命、95%较高攻击、60%防御、120%魔抗、速度90、回复6%；狂暴士兵75%生命、145%较高攻击、25%防御、120%魔抗、速度115，每次行动后失去5%最大生命。攻击均为物理。\n\n角色定位参考：[宿主重装组长](https://prts.wiki/w/宿主重装组长)、[宿主流浪者](https://prts.wiki/w/宿主流浪者)、[狂暴宿主士兵](https://prts.wiki/w/狂暴宿主士兵)。上述比例为本作回合制改编。切城N01-3路障350生命/40防御/20魔抗；黑蛇N01-4路障500生命/60防御/30魔抗。\n\n## 统一行动逻辑\n\n生成合法ABC、体术、休整、防御及合法目标与分支，逐项克隆战斗并执行。效用计入双方生命、护盾、技力、状态、行动条、召唤存活与任务进度；博士生存权重较高。保留立即效用前三动作，模拟下一行动者一次旧策略回应，按35%立即效用+65%回应后效用选招。队友、敌人、召唤物共享同一入口，剧情限定动作单独保留。非法目标遵守嘲讽、隐匿、不可选中。\n\n这是有限搜索，不能证明全局最优；任务、长线资源和连锁控制仍需玩家决策。自由模拟可以观察与试用。\n';write('剧情单位_完整数值与招式',units);
let growth='# 战力、转盘与成长 · v17\n\n五轴独立抽取；档内初值位于前20%级分，按相邻锚点几何插值。无跨级伤害修正。出生地和种族只作背景；感染者生命×0.9、技艺×1.15，非感染者生命×1.1。\n\n| 分级 | 权重 | 实际概率 | 五轴数值锚点 | 中性生命 | 技力上限 |\n|---|---:|---:|---:|---:|---:|\n';const total=WEIGHTS.reduce((a,b)=>a+b,0);TIERS.forEach((n,i)=>growth+=`| ${tierLabel(i)} | ${WEIGHTS[i]} | ${(100*WEIGHTS[i]/total).toFixed(6)}% | ${ANCHORS[i]} | ${12*ANCHORS[i]} | ${Math.floor(40+60*Math.sqrt(ANCHORS[i]/100))} |\n`);
growth+='\n综合级分=25%耐受+15%强度+20%适应性+30%较高攻击项+10%较低攻击项；最高不超过中位项+2。王庭以上至少3项达到该档。等级仅是面板结果，不参与伤害。成长后重新评级；初始身份修正也计入。\n\n王庭/神明/崛起日常训练效率15%/4%/1%，同水平实战保留完整成长。进入10—16级需8/12/18/24/32/42/56实战凭证，受阻积累最多0.25级。真实胜利且敌人综合档处于自身−1至+2范围，每项+2凭证；完成保护/撤离不冒充击杀；同档矢量投影胜利每项+2。\n\n## 成长天赋\n\n不是生命天赋，不提高开局面板。沿用参考网页的九档资质与倍率：\n\n| 等级 | 抽取权重 | 成长倍率 |\n|---|---:|---:|\n';for(const g of DATA.talents.grades)growth+=`| ${g.grade} | ${g.weight}% | ×${g.training_multiplier} |\n`;
growth+='\n## 每日同一个转盘\n\n| 项目 | 概率 | 效果 |\n|---|---:|---|\n';for(const p of DAILY_PROJECTS)growth+=`| ${p.name} | ${p.weight}% | ${p.vector?'抽取岛上普通干员技艺，再50%同档/50%较低档评级；最下档只能同档':p.axis!==undefined?'对应轴基础+6/9/14，概率55%/30%/15%，乘天赋'+(p.m?'；熟练度基础+'+p.m+'乘天赋取整':''):p.supply?'补给+'+p.supply:'恢复全部生命'} |\n`;
growth+='\n矢量突破胜利：全五轴基础+max(2,floor(敌方档锚点×0.045))乘天赋，熟练度+(12+敌档)×天赋取整；投影满血独立训练，不消耗战役补给、不改变战役生命，失败不触发铁人死亡。每日结束恢复15%生命。\n\n剧情作战胜利：全五轴基础+max(2,min(敌最高档锚点×0.012,自身最弱轴数值×0.05))乘天赋。熟练度使用场景与招式使用奖励，单次至多40，满200停止。失败保留少量熟练度，不发胜利指标奖励。成长记录显示基础数值×天赋×高阶效率→实际面板增加量；最大生命还计入身份乘数与取整。\n\n## 准备日与剧情节点\n\n| 节点 | 独立开局准备日 | 连贯转场准备日 |\n|---|---:|---:|\n';DATA.campaign.nodes.forEach((n,i)=>growth+=`| ${n.id} ${n.name} | ${[20,18,18,16,16,14,30,24,22,20,18,16][i]} | ${i?TRANSITION[i-1]:'从N01起20'} |\n`);
growth+='\n从N01连续全程共168准备日。每节点4场作战。没有可选计划、伤势或场间补给操作；初始6补给，后勤盘可补充。战内急救2补给回全队25%生命，野战护理4补给回75%；消耗博士本次行动，不复活。默认铁人死亡结束整局；可取消铁人，预留1日与3补给取得节点一次重试。胜利自动进入下一场；跨节点有准备日时进入营地。\n\n## 各场任务\n\n';for(const n of DATA.campaign.nodes){growth+=`### ${n.id} ${n.name}\n\n`;for(const b of n.battles)growth+=`- **${b.id} ${b.title}**：${narrative(b)}\n  - 任务：${mission(b)}\n  - 队友：${b.allies.map(id=>DATA.campaign.units.find(u=>u.id===id)?.name).join('、')||'无'}；敌方：${b.enemies.map(id=>DATA.campaign.units.find(u=>u.id===id)?.name).join('、')}。具体评级/数值/招式见剧情单位表。\n`;}write('战力成长与战役实装',growth);
write('完整游戏流程图',`# 泰拉命运转盘 · 完整流程 v17\n\n\`\`\`mermaid\nflowchart TD\n A[标题：博士 / 默认铁人 / 可选传奇之路] --> B[出生地 → 种族 → 感染身份 → 穿越节点]\n B --> C[源石技艺：名称附原型 → 五轴独立战力 → 成长天赋]\n C --> D[查看档案：数值 / 综合分级 / 天赋倍率]\n D --> E[节点营地：剩余准备日]\n E --> F[每日成长转盘]\n F --> G{抽到项目}\n G --> H[五轴训练或技艺修行：倍率与实际增长]\n G --> I[矢量突破：岛上技艺转盘 → 对手评级转盘]\n G --> J[医疗休养或后勤]\n I --> K[投影战斗：胜利增五轴与熟练度 / 失败返回]\n H --> L[扣1日 / 日终回复生命 / 重算评级]\n K --> L\n J --> L\n L --> E\n E --> M[出发 / 展示本场任务与双方阵列]\n M --> N[回合战斗：体术 / ABC / 休整 / 防御]\n N --> O[敌人与队友及召唤物自动按行动条行动]\n O --> P{本场结果}\n P -->|成功| Q[指标成长与熟练度结算]\n Q -->|还有场次且无需准备| N\n Q -->|本节点结束| R{还有节点吗}\n R -->|有| E\n R -->|无| S[结局档案与成长记录]\n P -->|博士死亡且铁人| S\n P -->|失败但存活| T[撤离或标准模式有限重试]\n T --> R\n T -->|重试| M\n N --> U[战内补给：显示数量 / 消耗博士行动]\n U --> O\n V[独立模拟：任选181技艺 / 熟练度 / 敌人] --> W[不覆盖正式旅程与成长]\n\`\`\`\n\n11项建角及每日项目、突破技艺与分级全部使用旋转转盘；最后天赋有独立揭晓步骤。M100专精，M200升变；异常状态与条件限制见技能侧栏。自动推进保留上一场成长日志；档案可追溯全部剧情成长。\n`);
console.log({cards:rows.length,withoutReview:rows.filter(c=>!review(c)).length,review:rows.filter(review).length,npcs:nr.length,summonNames:audit.summonNames.length});
