import fs from 'node:fs';import {CARDS,BY_ID,actionFor,actionText,evolvedCard,PASSIVE_TEXT} from '../dist/cards.js';import {DATA} from '../dist/data.js';import {WEIGHTS,TIERS,LETTERS,derive,rollStat,seedNumber} from '../dist/math.js';
const dir='artifacts/v21';fs.mkdirSync(dir,{recursive:true});
const old=fs.existsSync(dir+'/baseline.json')?JSON.parse(fs.readFileSync(dir+'/baseline.json')):CARDS.map(card=>({card})),total=WEIGHTS.reduce((a,b)=>a+b),records=[];
for(const c of CARDS){const raw=DATA.arts.cards.find(r=>r.art_id===c.id);const variants=[0,100,200].map(m=>{const v=evolvedCard(c,m);return{mastery:m,name:v.name,source:v.source,resource:v.resource,cap:v.cap,initial:v.initial,passive:v.passive.map(p=>PASSIVE_TEXT[p]),actions:c.actions.map((_,i)=>{const a=actionFor(c,i,m);return{...a,actualCost:Math.ceil(a.cost*.9),text:actionText(a)};})};});records.push({id:c.id,name:c.name,source:c.source,pool:c.pool,url:c.url,name_review:raw.name_review,needsReview:raw.name_review==='review_required'||(!/^[3-6]星$/.test(raw.source_rarity)&&raw.name_review!=='user_specified_name'),lore_status:raw.lore_status,original:(old.find(r=>r.card.id===c.id)?.card||c).actions,variants});}
const state={rng:seedNumber('v21-distribution')},counts=Array(17).fill(0);for(let i=0;i<100000;i++)counts[Math.floor(rollStat(state))]++;
const summary={cards:records.length,normal:records.filter(r=>r.pool==='normal').length,hidden:records.filter(r=>r.pool==='hidden').length,review:records.filter(r=>r.needsReview).length,draws:100000,distribution:WEIGHTS.map((w,i)=>({tier:LETTERS[i],category:TIERS[i],probability:w/total,observed:counts[i]/100000,stats:derive(Array(5).fill(i))})),mastery:{artsTraining:5,adaptabilityTraining:2,vector:'3+floor(enemyTier/4)',story:'victory 4–10, defeat 1',talentMultiplier:1,thresholds:[100,200]},progressionAudit:'182技艺三档配置逐招比较；基础模式与21项用户指定机制由 fixtures/v19-protected.json 回归保护；自动升级不增加费用和冷却、不移除基础效果。'};
fs.writeFileSync(dir+'/numeric-audit.json',JSON.stringify(summary,null,2));fs.writeFileSync(dir+'/arts-v21.json',JSON.stringify(records,null,2));
const cn=s=>String(s).replace(/([0-9.%＋+−×()（）/]+)Q/g,'$1较高攻击强度').replace(/([0-9.%＋+−×()（）/]+)H/g,'$1最大生命').replace(/([0-9.%＋+−×()（）/]+)A/g,'$1体术强度').replace(/([0-9.%＋+−×()（）/]+)P/g,'$1技艺强度').replace(/([0-9.%＋+−×()（）/]+)D/g,'$1防御').replace(/([0-9.%＋+−×()（）/]+)R/g,'$1魔抗');
const target=t=>({enemy_one:'敌单体',enemy_all:'敌全体',enemy_up_to_three:'至多3敌',enemy_up_to_two:'至多2敌',enemy_two:'敌方双目标',enemy_three:'敌方三目标',self:'自身',ally_one:'友单体',ally_all:'友全体',ally_main_one:'友方主体',ally_healable_one:'可治疗友方',ally_all_mains:'友方全体主体',choose_mode:'所选分支',recorded_targets:'记录目标'}[t]||t);
let text='# 源石技艺完整实装表 v21\n\n2026-10-02。由网站执行数据直接导出，共182项（普通151、隐藏31）。技能数值为同人游戏参数，百科链接用于原型依据；对话中指定过的21项机制保持原目标、资源、召唤数量和触发模式，只增强数值。\n\n- M100自动专精：A/B伤害系数×1.15，各基础费用−3。\n- M200自动升变：A/B系数再×1.20，各基础费用再−2；C解锁、系数通常×1.20、基础费用−4；提丰C按指定最终799%固定。专精、升变及熟练度收益不乘天赋。\n- 异格保留原招式和资源，叠加异格身份、特性与增益；不再用异格动作覆盖原动作。特殊冬痕升变依用户指定保留冰封／雪怪／强退。\n- 下文费用已按90%折算并向上取整；A/B无冷却，强C通常最多1回合；缪尔赛思四流形C按本次要求为2回合。特殊触发条件在正文列出。\n- 逻各斯C改为至多3目标高伤、敌方行动条−60、己方全体盾；莫斯提马、艾雅法拉、仇白、银灰纠正决战技群攻定位。这5项原型纠正不涉及此前指定的21项机制。\n\n';
for(const [title,list] of [['无需名称审阅（原型技能名／已指定名称）',records.filter(r=>!r.needsReview)],['集中名称审阅（敌方与待审名称）',records.filter(r=>r.needsReview)]]){text+='## '+title+'\n\n';for(const c of list){text+=`### ${c.id} · ${c.name}（${c.source}）${c.pool==='hidden'?'【隐藏】':''}\n\n[原型资料](${c.url}) · ${c.name_review}\n\n`;for(const v of c.variants){text+=`**M${v.mastery}${v.mastery===100?' · 自动专精':v.mastery===200?' · 自动升变':''} · ${v.name}（${v.source}）**\n\n`;if(v.resource)text+=`资源：${v.resource}，初始${v.initial}，上限${v.cap}。\n\n`;if(v.passive.length)text+=v.passive.map(t=>'- '+cn(t)).join('\n')+'\n\n';for(const a of v.actions)text+=`- **${a.button} · ${a.name} / ${a.label}**：${a.actualCost}技力；${target(a.target)}；冷却${a.cd}${a.limit?'；本场限'+a.limit+'次':''}${a.fromTurn?'；第'+a.fromTurn+'次机会起':''}${a.fromRound?'；第'+a.fromRound+'战场轮起':''}。${cn(a.text)}\n`;text+='\n';}}}
fs.writeFileSync('源石技艺_完整实装与集中审阅_v21.md',text);
const table=summary.distribution.map(r=>`| ${r.tier} | ${r.category} | ${(r.probability*100).toFixed(3)}% | ${r.stats.H} | ${r.stats.D} | ${r.stats.A} | ${r.stats.P} | ${r.stats.R} | ${r.stats.Emax} |`).join('\n');
fs.writeFileSync('数值与成长调整_v21.md',`# 数值与成长调整 v21\n\n## 开局转盘\n\nD系列总权重从约62%降到28%；C系列43.002%；B系列20.5%；A系列7.8%；S及以上0.698%。各轴独立抽取，不能把单轴概率当作综合评级概率。高阶仍严格递减；属性锻炼后动态重算评级。\n\n以下是各档下边界、非感染者面板，实际抽取还含档内浮动；感染者生命系数0.9、技艺强度×1.15，非感染者生命系数1.1。\n\n| 字母 | 分级 | 单轴概率 | 生命上限 | 防御 | 体术强度 | 技艺强度 | 魔抗 | 技力上限 |\n|---|---|---:|---:|---:|---:|---:|---:|---:|\n${table}\n\n## 技力与伤害\n\n技力上限=floor(100+100×sqrt(魔抗/100))；每次自身机会自然恢复=max(12,floor(上限×6%))；休整恢复=max(32,ceil(上限×16%))及8%最大生命。D−技力上限163，C−上限200。召唤物无技力时不额外生成容量。剧情单位容量至少为公式值。常规A/B/C基础伤害系数分别×1.30/1.40/1.65，隐藏×1.15/1.20/1.35；控制时长、召唤数量、资源消耗模式不因该倍率改变。特殊伤害记录本招系数，延迟与召唤指令按同一系数执行；独立召唤攻击仍用自身面板。\n\n剧情NPC的成品招式直接按配置执行，不重复叠加博士的熟练度专精倍率。博士及训练投影使用技艺熟练度成长。无任何按等级差修改伤害的公式。\n\n## 熟练度、专精、升变\n\n熟练度与天赋倍率分离：技艺修行+5，适应性研习+2；矢量胜利+3+floor(对手分级序号/4)；剧情胜利基础4–8并按不同ABC练习最多+2，总计4–10；失败+1；上限200。天赋仍乘五项指标的训练／战斗成长。不同天赋在相同事件与对手条件下获得相同熟练度，升变数值也相同。\n\n100自动应用A/B专精；200自动应用升变与C。不再选择牺牲另一招费用的专精，也不再支付额外费用、等待额外回合或限制次数换取升变。异格保留基础招式并叠加正收益；此前要求的冬痕召唤／强退等专属模式保持。\n\n## 结算体验与存档\n\n剧情或矢量胜利进入成长页：六项派生数值逐项显示旧值→新值与绿色增幅，播放数字增长和进度条延伸；同步显示综合评级与熟练度突破。确认后自动进入下一战或准备日。奖励结算与确认分离，刷新／导入可恢复该页；重复结算不发第二份成长。战场增加蓝色技力条，档案同时显示生命、体术、术强、防御、魔抗与技力。旧存档保留既有熟练度与成长，按剩余比例迁移技力容量，清除旧专精／极式的负收益选项。\n`);
console.log(JSON.stringify({cards:summary.cards,review:summary.review,D:counts.slice(0,3).reduce((a,b)=>a+b)/100000}));
